services:
  taskflow_api:
    container_name: taskflow_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
      - DatabaseName=TaskFlowDB

  mongodb:
    container_name: mongo_db
    image: mongo:8.0
    ports:
      - "27017:27017"